
project_id = "pkvrxhczpvmopgzgcqmk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[functions]
[functions.check-subscription]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-sync-plans]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-all-users]
verify_jwt = true

[functions.get-admin-users]
verify_jwt = true
