
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkvrxhczpvmopgzgcqmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrdnJ4aGN6cHZtb3BnemdjcW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDE1NzEsImV4cCI6MjA2MjM3NzU3MX0.8Cp2c2UXtRv7meUl8KNx4ihgdEhUTUd_dLeYDnUQn9o";
// For server-side only, don't reference in client-side code
const SUPABASE_SERVICE_ROLE_KEY = ''; // Empty string for client-side

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Admin client with service role key - only use on the server side
// This should ideally only be used in edge functions or server components
// For client-side admin operations, proxy requests through an API endpoint
export const createAdminClient = () => {
  // We don't have access to service role key in the browser
  // This function will return the regular client in browser environments
  // Edge functions will have proper environment variables set
  return supabase;
};
